global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
  external_labels:
    monitor: 'monitor'

# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
  # Scrape Prometheus itself every 5 seconds.
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'

    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.99.100:9100', '192.168.99.101:9100']

  - job_name: 'haproxy'

    scrape_interval: 1s

    static_configs:
      - targets: ['192.168.99.100:9101']
